export const routes = {
  home: "/",
  products: "/produtos",
  productRecentlyOpened: "/produtos/empresas-recem-abertas",
  productAgencies: "/produtos/agencias-marketing",
  productAccounting: "/produtos/contabilidades",
  request: "/solicitar-planilha/",
  productCustom: "/solicitar-planilha/",
  productSample: "/solicitar-planilha/",
  builder: "/solicitar-planilha/",
  audiences: "/para-quem-e",
  howItWorks: "/como-funciona",
  baseFields: "/campos-da-base",
  faq: "/faq",
  contact: "/contato",
  about: "/sobre",
  privacy: "/politica-de-privacidade",
  suppression: "/politica-de-supressao",
  cookies: "/politica-de-cookies",
  terms: "/termos-de-uso",
  checkoutSuccess: "/compra/sucesso",
  checkoutPending: "/compra/pendente",
  checkoutError: "/compra/erro",
  orderStatus: "/pedido/",
  order: "/pedido/[id]",
  admin: "/admin",
  solucoes: "/solucoes",
  sitesLandingPages: "/solucoes/sites-landing-pages",
  leads: "/leads",
  prospectaWeb: "/prospecta-web",
  segmentos: "/segmentos",
  planos: "/planos",
  conteudo: "/conteudo",
  amostra: "/amostra",
  leadsB2b: "/leads-b2b",
  sites: "/sites",
  landingPages: "/landing-pages",
  automacao: "/automacao",
  projetos: "/projetos",
} as const;

export const publicRoutes = [
  routes.home,
  routes.products,
  routes.productRecentlyOpened,
  routes.productAgencies,
  routes.productAccounting,
  routes.productCustom,
  routes.productSample,
  routes.builder,
  routes.audiences,
  routes.howItWorks,
  routes.baseFields,
  routes.faq,
  routes.contact,
  routes.about,
  routes.privacy,
  routes.suppression,
  routes.cookies,
  routes.terms,
  routes.checkoutSuccess,
  routes.checkoutPending,
  routes.checkoutError,
  routes.orderStatus,
  routes.solucoes,
  routes.sitesLandingPages,
  routes.leads,
  routes.prospectaWeb,
  routes.segmentos,
  routes.planos,
  routes.conteudo,
  routes.amostra,
  routes.leadsB2b,
  routes.sites,
  routes.landingPages,
  routes.automacao,
  routes.projetos,
];

export const legacyRedirects = ["/blog", "/conteudos", "/solucoes", "/insights"];
